apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-k3d-demo.fullname" . }}
  labels:
    {{- include "python-k3d-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "python-k3d-demo.selectorLabels" . | nindent 4 }}
